# Generated by Django 5.0 on 2025-07-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazendascdst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Vacina')),
                ('validade_dias', models.IntegerField(default=30, verbose_name='Validade (dias)')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='SEM_ID', max_length=65, unique=True, verbose_name='Identificador')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_de_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazendascdst.fazenda')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_aplicacao', models.DateField(verbose_name='Data de Aplicação')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gado.animal', verbose_name='Animal')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gado.vacina', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinações',
            },
        ),
    ]
