# Generated by Django 5.2.4 on 2025-07-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendascdst', '0003_fazenda_area_piquete'),
        ('gado', '0002_animal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='piquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='fazendascdst.piquete', verbose_name='Piquete'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.CharField(choices=[('CORTE', 'Gado de Corte'), ('LEITE', 'Gado Leiteiro')], default='CORTE', max_length=10, verbose_name='Tipo de Gado'),
        ),
    ]
