# Generated by Django 5.2.4 on 2025-07-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendascdst', '0004_alter_piquete_unique_together_remove_piquete_fazenda_and_more'),
        ('gado', '0004_fix_identificador_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='piquete',
        ),
        migrations.AddField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='fazendascdst.lote', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='identificador',
            field=models.IntegerField(blank=True, null=True, verbose_name='Identificador'),
        ),
    ]