# Generated by Django 5.2.3 on 2025-07-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gado', '0008_animal_user_vacina_user_vacinacao_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='observacoes_baixa',
            field=models.TextField(blank=True, help_text='Motivo da baixa ou observações sobre a saída do animal', null=True, verbose_name='Observações de Baixa'),
        ),
    ]
