# Generated by Django 5.2.3 on 2025-07-15 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_movimentacao_estoque_user_produto_user'),
        ('fazendascdst', '0006_fazenda_user_lote_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('baixa', 'Baixa')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('peso_medio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_manejo', models.CharField(blank=True, max_length=255, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazendascdst.lote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
