# Generated by Django 5.0 on 2025-07-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localização', models.TextField()),
                ('data_de_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
