# Generated by Django 5.2.4 on 2025-07-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendascdst', '0002_fazenda_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (hectares)'),
        ),
        migrations.CreateModel(
            name='Piquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Piquete')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área (hectares)')),
                ('capacidade_maxima', models.IntegerField(blank=True, null=True, verbose_name='Capacidade Máxima de Animais')),
                ('data_de_cadastro', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piquetes', to='fazendascdst.fazenda')),
            ],
            options={
                'verbose_name': 'Piquete',
                'verbose_name_plural': 'Piquetes',
                'unique_together': {('nome', 'fazenda')},
            },
        ),
    ]
