# Generated by Django 5.2.4 on 2025-07-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendascdst', '0003_fazenda_area_piquete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='piquete',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='piquete',
            name='fazenda',
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Lote')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área (hectares)')),
                ('capacidade_maxima', models.IntegerField(blank=True, null=True, verbose_name='Capacidade Máxima de Animais')),
                ('data_de_cadastro', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='fazendascdst.fazenda')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
