# Generated by Django 5.2.4 on 2025-07-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazendascdst', '0004_alter_piquete_unique_together_remove_piquete_fazenda_and_more'),
        ('gado', '0005_remove_animal_piquete_animal_lote_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piquete',
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('nome', 'fazenda')},
        ),
    ]
