# Generated by Django 5.2.3 on 2025-07-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazendascdst', '0006_fazenda_user_lote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='area',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='area',
        ),
    ]
