# Generated by Django 5.2.3 on 2025-07-16 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observacaorelatorio',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Observação de Relatório', 'verbose_name_plural': 'Observações de Relatórios'},
        ),
        migrations.AlterUniqueTogether(
            name='observacaorelatorio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='observacaorelatorio',
            name='data_referencia',
            field=models.DateField(blank=True, help_text='Data de referência (se aplicável)', null=True),
        ),
        migrations.AddField(
            model_name='observacaorelatorio',
            name='lote',
            field=models.CharField(blank=True, help_text='Nome do lote (se aplicável)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='observacaorelatorio',
            name='tipo',
            field=models.CharField(blank=True, choices=[('LOTE', 'Lote'), ('VACINACAO', 'Vacinação'), ('BAIXA', 'Baixa de Animais'), ('GERAL', 'Observação Geral')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='observacaorelatorio',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='observacaorelatorio',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observação (opcional)', null=True),
        ),
        migrations.RemoveField(
            model_name='observacaorelatorio',
            name='data_atualizacao',
        ),
    ]
